-- Seed file to populate the database with production data
-- This file is processed by Supabase CLI during db reset
-- Note: Profiles must be seeded first before other tables due to foreign key constraints
-- The seed files are loaded in this order:
-- 1. profiles (users)
-- 2. songs
-- 3. lessons
-- 4. lesson_songs
-- 5. task_management
-- Each individual seed file is a separate transaction